### ISSUE TITLE
IDE stall

### ISSUE THREAD

**Issue by joubertc** [dice-project/DICE-Platform#4]
Dear all,

Here is a reported issue on the DICE IDE:

"please see below a minor bug we are experiencing with the IDE.
Basically we are trying to open in Papyrus the models ad\* and sd*
here: https://github.com/dice-project/DICE-Simulation/tree/m2m-redesign/es.unizar.disco.pnml.m2m/examples/

With Eclipse+Papyrus there's no problem. We create a new project, copy the 3 folders under it in the workspace, and the Papyrus opens the models fine.

With DICE IDE on two computers we first faced the issue that it did not start. We had to add -vm C:\Program Files\Java\jre7\bin\javaw to the DICE ini. I guess we did not have the environmental variable for Java set correctly, but this is probably the default since we had this on two computers. Can we alert the user about this issue in the README.md on github?

One DICE IDE is started, repeating the same steps with Papyrus makes the IDE stall. I changed the vmargs to but no ch-Xms2048m -Xmx3096m but no changes. I use Windows 10. My colleague seemed to use an older Windows, probably XP."

Thanks in advance
BR

Note: this bug is originally provided by @gcasale

**Comment by abelgomez** [comment]
Regarding the -vm argument, it is important to note that Eclipse Mars requires Java 7 for all Mars downloads (https://wiki.eclipse.org/Eclipse/Installation#Eclipse_4.5_.28Mars.29).

Thus, I think it's fine to make that explicit in the documentation but the issue should be considered as a misconfiguration of the user's environment and not as an IDE's fault.

**Comment by marcgise** [comment]
The problem you're having when importing a Papyrus model, is well known. You have the same issue when using the IDE of Papyrus.

There is a workaround here: http://stackoverflow.com/questions/28088768/papyrus-restore-diagram
1. Create a new project or import an existing one
2. Make sure to have the Papyrus perspective opened. By default it is opened on DICE IDE.
3. Open the diagram
4. Browse over the "Model Explorer" view looking for the "Diagram" element
5. Repeat step #4 for each diagram
6. Now it is solved

This is due to Papyrus creates an associated internal file to manage the diagrams (placed on $WORKSPACE/.metadata/.plugins/org.eclipse.papyrus.infra.core, one folder per project, one file *.sash per model). When you import an external project, Papyrus doesn't know how to find the diagrams until you open one with the previous steps.

**Comment by marcgise** [comment]
Regarding the problems with Java, check wich version did you downloaded (x86 or x64 bit), and check your Java version and if you have it defined in the PATH.

Regarding the configuration parameters -Xms2048m -Xmx3096m, by default they are set with a common values. There is not an optimal better values, due to this values depends on the memory your machine has. Maybe you can set higher values and DICE IDE doesn't run. With the default provided values, DICE IDE will usually run.
